[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"

# Настройки для Railway
[service]
# Использовать последнюю версию Node.js
nodeVersion = "18"

# Настройки здоровья приложения
[[services.healthchecks]]
interval = 30
timeout = 10
retries = 3
path = "/"

# Перезапускать при сбоях
[services.restart]
maxRetries = 3
delay = "10s"
